### ISSUE TITLE
mail --mbox doesn't produce an mbox file

### ISSUE THREAD

**Issue by kephas** [emacsorphanage/magit-stgit#11]
When running `stg mail --mbox` in the shell, it produces the mbox data in its standard output, that you need to redirect to an mbox file. The mbox data is clearly readable in the `magit-process` buffer and no file is created.

**Comment by tarsius** [comment]
I don't really maintain this anymore and the last commit by the original author is from three years ago. so you will have to implement this yourself.

I would recommend removing the argument and instead adding a new command to the popup. The command would have to insert subprocesses output into a temporary buffer and then save it to a file.

**Comment by kephas** [comment]
Thanks for the quick answer, then!

**Comment by tarsius** [comment]
Also see #12.

**Comment by llvilanova** [comment]
Ummm, I haven't used this one in a long while. @tarsius how do I get the stdout of magit-run-stgit-async? Is `magit-stgit-lines` and some new temporary buffer the way to go?

**Comment by tarsius** [comment]
> Is `magit-stgit-lines` and some new temporary buffer the way to go?

That sounds about right.

**Comment by tarsius** [comment]
Closing since this is no longer maintained.
